-- ===========================================================================
-- Serensa Complete Database Schema (PostgreSQL)
-- ===========================================================================
-- Purpose: Full portable SQL for manual database creation
-- Includes: Django auth tables + all Serensa app models
-- Usage: psql -U <user> -d <dbname> -f serensa_complete_schema.sql
--
-- Prerequisites:
--   - PostgreSQL 10+ with UUID extensions (if needed)
--   - Database created and permissions granted to user
-- ===========================================================================

BEGIN;

-- ===========================================================================
-- PART 1: Django Core/Auth Tables (required by the User custom model)
-- ===========================================================================

-- =========================
-- Table: auth_user (Custom User Model)
-- =========================
CREATE TABLE IF NOT EXISTS auth_user (
    id SERIAL PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE NULL,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    username VARCHAR(150) NOT NULL UNIQUE,
    first_name VARCHAR(150) NOT NULL DEFAULT '',
    last_name VARCHAR(150) NOT NULL DEFAULT '',
    email VARCHAR(254) NOT NULL DEFAULT '',
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    date_joined TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auth_user_username
    ON auth_user (username);

-- =========================
-- Table: auth_group
-- =========================
CREATE TABLE IF NOT EXISTS auth_group (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);

-- =========================
-- Table: auth_group_permissions
-- =========================
CREATE TABLE IF NOT EXISTS auth_group_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    CONSTRAINT fk_auth_group_permissions_group
        FOREIGN KEY (group_id)
        REFERENCES auth_group (id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_auth_group_permission
        UNIQUE (group_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_group_permissions_group_id
    ON auth_group_permissions (group_id);

-- =========================
-- Table: auth_user_groups
-- =========================
CREATE TABLE IF NOT EXISTS auth_user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    CONSTRAINT fk_auth_user_groups_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_auth_user_groups_group
        FOREIGN KEY (group_id)
        REFERENCES auth_group (id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_auth_user_group
        UNIQUE (user_id, group_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_groups_user_id
    ON auth_user_groups (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_user_groups_group_id
    ON auth_user_groups (group_id);

-- =========================
-- Table: auth_permission
-- =========================
CREATE TABLE IF NOT EXISTS auth_permission (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    content_type_id INTEGER NOT NULL,
    codename VARCHAR(100) NOT NULL,
    CONSTRAINT uniq_auth_permission_content_type_codename
        UNIQUE (content_type_id, codename)
);

CREATE INDEX IF NOT EXISTS idx_auth_permission_content_type_id
    ON auth_permission (content_type_id);

-- =========================
-- Table: auth_user_permissions
-- =========================
CREATE TABLE IF NOT EXISTS auth_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    CONSTRAINT fk_auth_user_permissions_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_auth_user_permissions_permission
        FOREIGN KEY (permission_id)
        REFERENCES auth_permission (id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_auth_user_permission
        UNIQUE (user_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_permissions_user_id
    ON auth_user_permissions (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_user_permissions_permission_id
    ON auth_user_permissions (permission_id);

-- =========================
-- Table: django_content_type
-- =========================
CREATE TABLE IF NOT EXISTS django_content_type (
    id SERIAL PRIMARY KEY,
    app_label VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    CONSTRAINT uniq_django_content_type_app_label_model
        UNIQUE (app_label, model)
);

-- =========================
-- Table: django_migrations
-- =========================
CREATE TABLE IF NOT EXISTS django_migrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    applied TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- Table: django_session
-- =========================
CREATE TABLE IF NOT EXISTS django_session (
    session_key VARCHAR(40) PRIMARY KEY,
    session_data TEXT NOT NULL,
    expire_date TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_django_session_expire_date
    ON django_session (expire_date);

-- ===========================================================================
-- PART 2: Serensa App Tables
-- ===========================================================================

-- =========================
-- Table: sensa_shop
-- =========================
CREATE TABLE IF NOT EXISTS sensa_shop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    shop_type VARCHAR(20) NOT NULL DEFAULT 'retail',
    parent_shop_id BIGINT NULL,
    location VARCHAR(180) NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_sensa_shop_type
        CHECK (shop_type IN ('restaurant', 'retail', 'bar', 'other')),
    CONSTRAINT fk_sensa_shop_parent_shop
        FOREIGN KEY (parent_shop_id)
        REFERENCES sensa_shop (id)
        ON DELETE CASCADE
);

-- Parent shop names are unique at top level
CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_sensa_shop_parent_name
    ON sensa_shop (name)
    WHERE parent_shop_id IS NULL;

-- Subshop names are unique within each parent
CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_sensa_shop_subshop_name
    ON sensa_shop (parent_shop_id, name)
    WHERE parent_shop_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sensa_shop_parent_shop_id
    ON sensa_shop (parent_shop_id);

CREATE INDEX IF NOT EXISTS idx_sensa_shop_active
    ON sensa_shop (active);

-- =========================
-- Table: sensa_userprofile
-- =========================
CREATE TABLE IF NOT EXISTS sensa_userprofile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'vendor',
    phone_number VARCHAR(20) NOT NULL DEFAULT '',
    CONSTRAINT chk_sensa_userprofile_role
        CHECK (role IN ('admin', 'vendor')),
    CONSTRAINT fk_sensa_userprofile_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sensa_userprofile_phone_number
    ON sensa_userprofile (phone_number);

CREATE INDEX IF NOT EXISTS idx_sensa_userprofile_role
    ON sensa_userprofile (role);

-- ============================================
-- Table: sensa_userprofile_assigned_shops (M2M)
-- ============================================
CREATE TABLE IF NOT EXISTS sensa_userprofile_assigned_shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userprofile_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    CONSTRAINT fk_sensa_userprofile_assigned_shops_userprofile
        FOREIGN KEY (userprofile_id)
        REFERENCES sensa_userprofile (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sensa_userprofile_assigned_shops_shop
        FOREIGN KEY (shop_id)
        REFERENCES sensa_shop (id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_sensa_userprofile_assigned_shops
        UNIQUE (userprofile_id, shop_id)
);

CREATE INDEX IF NOT EXISTS idx_sensa_userprofile_assigned_shops_userprofile_id
    ON sensa_userprofile_assigned_shops (userprofile_id);

CREATE INDEX IF NOT EXISTS idx_sensa_userprofile_assigned_shops_shop_id
    ON sensa_userprofile_assigned_shops (shop_id);

-- =========================
-- Table: sensa_dailyentry
-- =========================
CREATE TABLE IF NOT EXISTS sensa_dailyentry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    opening_stock NUMERIC(14,2) NOT NULL,
    stock_added NUMERIC(14,2) NOT NULL,
    expenses NUMERIC(14,2) NOT NULL,
    debts NUMERIC(14,2) NOT NULL,
    closing_stock NUMERIC(14,2) NOT NULL,
    cash_received NUMERIC(14,2) NOT NULL,
    sales_value NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    notes TEXT NOT NULL DEFAULT '',
    submitted_by_id INTEGER NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensa_dailyentry_shop
        FOREIGN KEY (shop_id)
        REFERENCES sensa_shop (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sensa_dailyentry_submitted_by
        FOREIGN KEY (submitted_by_id)
        REFERENCES auth_user (id)
        ON DELETE SET NULL,
    CONSTRAINT uniq_sensa_dailyentry_shop_entry_date
        UNIQUE (shop_id, entry_date),
    CONSTRAINT chk_sensa_dailyentry_opening_stock_non_negative
        CHECK (opening_stock >= 0),
    CONSTRAINT chk_sensa_dailyentry_stock_added_non_negative
        CHECK (stock_added >= 0),
    CONSTRAINT chk_sensa_dailyentry_expenses_non_negative
        CHECK (expenses >= 0),
    CONSTRAINT chk_sensa_dailyentry_debts_non_negative
        CHECK (debts >= 0),
    CONSTRAINT chk_sensa_dailyentry_closing_stock_non_negative
        CHECK (closing_stock >= 0),
    CONSTRAINT chk_sensa_dailyentry_cash_received_non_negative
        CHECK (cash_received >= 0),
    CONSTRAINT chk_sensa_dailyentry_sales_value_non_negative
        CHECK (sales_value >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sensa_dailyentry_shop_id
    ON sensa_dailyentry (shop_id);

CREATE INDEX IF NOT EXISTS idx_sensa_dailyentry_entry_date
    ON sensa_dailyentry (entry_date DESC);

CREATE INDEX IF NOT EXISTS idx_sensa_dailyentry_submitted_by_id
    ON sensa_dailyentry (submitted_by_id);

-- =========================
-- Table: sensa_jengaapisettings
-- =========================
CREATE TABLE IF NOT EXISTS sensa_jengaapisettings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR(50) NOT NULL DEFAULT 'Jenga',
    account_reference VARCHAR(100) NOT NULL UNIQUE,
    balance_field_path VARCHAR(255) NOT NULL DEFAULT 'balance',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sensa_jengaapisettings_account_reference
    ON sensa_jengaapisettings (account_reference);

CREATE INDEX IF NOT EXISTS idx_sensa_jengaapisettings_updated_at
    ON sensa_jengaapisettings (updated_at DESC);

-- ================================
-- Table: sensa_bankbalancesnapshot
-- ================================
CREATE TABLE IF NOT EXISTS sensa_bankbalancesnapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    provider VARCHAR(50) NOT NULL DEFAULT 'Jenga',
    account_reference VARCHAR(100) NOT NULL DEFAULT '',
    balance NUMERIC(14,2) NOT NULL,
    raw_response TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_sensa_bankbalancesnapshot_fetched_at
    ON sensa_bankbalancesnapshot (fetched_at DESC);

CREATE INDEX IF NOT EXISTS idx_sensa_bankbalancesnapshot_provider
    ON sensa_bankbalancesnapshot (provider);

-- ===========================================================================
-- PART 3: Populate Django Content Types (required metadata)
-- ===========================================================================

-- Insert content types for auth models if not exist
INSERT INTO django_content_type (app_label, model)
VALUES
    ('auth', 'permission'),
    ('auth', 'user'),
    ('auth', 'group'),
    ('contenttypes', 'contenttype'),
    ('sessions', 'session'),
    ('sensa', 'user'),
    ('sensa', 'shop'),
    ('sensa', 'userprofile'),
    ('sensa', 'dailyentry'),
    ('sensa', 'jengaapisettings'),
    ('sensa', 'bankbalancesnapshot')
ON CONFLICT DO NOTHING;

-- ===========================================================================
-- PART 4: Sample Bootstrap Data (Optional - comment out if not needed)
-- ===========================================================================

-- Uncomment below to add sample initial data:

-- -- Create a superadmin user (use strong password in production!)
-- INSERT INTO auth_user 
--     (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)
-- VALUES 
--     ('pbkdf2_sha256$720000$RANDOMSALT$HASHEDPASSWORD', NULL, TRUE, 'admin', 'Admin', 'User', 'admin@serensa.local', TRUE, TRUE, CURRENT_TIMESTAMP)
-- ON CONFLICT DO NOTHING;

-- -- Create admin user profile
-- INSERT INTO sensa_userprofile (user_id, role, phone_number)
-- SELECT id, 'admin', '+254700000000'
-- FROM auth_user
-- WHERE username = 'admin'
-- ON CONFLICT DO NOTHING;

-- -- Create sample shop
-- INSERT INTO sensa_shop (name, shop_type, location, active, created_at)
-- VALUES 
--     ('Main Enterprise', 'restaurant', 'Nairobi', TRUE, CURRENT_TIMESTAMP)
-- ON CONFLICT DO NOTHING;

-- ===========================================================================
-- PART 5: Verification Queries (run after import to confirm)
-- ===========================================================================

-- SELECT 'Tables Created' as check_item, COUNT(*) as count
-- FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name LIKE 'sensa_%' OR table_name LIKE 'auth_%';

-- SELECT 'Auth User' as model, COUNT(*) as count FROM auth_user
-- UNION ALL
-- SELECT 'Shops', COUNT(*) FROM sensa_shop
-- UNION ALL
-- SELECT 'User Profiles', COUNT(*) FROM sensa_userprofile
-- UNION ALL
-- SELECT 'Daily Entries', COUNT(*) FROM sensa_dailyentry;

COMMIT;

-- ===========================================================================
-- End of Schema
-- ===========================================================================
