-- Serensa relational schema (derived from Django migrations)
-- Purpose: portable SQL reference of tables, constraints, and relationships.
-- Note: this file defines app tables and expects auth_user to already exist.

BEGIN;

-- =========================
-- Table: sensa_shop
-- =========================
CREATE TABLE IF NOT EXISTS sensa_shop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    location VARCHAR(180) NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- =========================
-- Table: sensa_userprofile
-- =========================
CREATE TABLE IF NOT EXISTS sensa_userprofile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'vendor',
    phone_number VARCHAR(20) NOT NULL DEFAULT '',
    CONSTRAINT chk_sensa_userprofile_role
        CHECK (role IN ('admin', 'vendor')),
    CONSTRAINT fk_sensa_userprofile_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE
);

-- Index created by db_index=True on phone_number.
CREATE INDEX IF NOT EXISTS idx_sensa_userprofile_phone_number
    ON sensa_userprofile (phone_number);

-- ============================================
-- Table: sensa_userprofile_assigned_shops (M2M)
-- ============================================
CREATE TABLE IF NOT EXISTS sensa_userprofile_assigned_shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userprofile_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    CONSTRAINT fk_profile_shop_userprofile
        FOREIGN KEY (userprofile_id)
        REFERENCES sensa_userprofile (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_profile_shop_shop
        FOREIGN KEY (shop_id)
        REFERENCES sensa_shop (id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_profile_shop
        UNIQUE (userprofile_id, shop_id)
);

CREATE INDEX IF NOT EXISTS idx_profile_shop_userprofile_id
    ON sensa_userprofile_assigned_shops (userprofile_id);

CREATE INDEX IF NOT EXISTS idx_profile_shop_shop_id
    ON sensa_userprofile_assigned_shops (shop_id);

-- =========================
-- Table: sensa_dailyentry
-- =========================
CREATE TABLE IF NOT EXISTS sensa_dailyentry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    opening_stock NUMERIC(14,2) NOT NULL,
    stock_added NUMERIC(14,2) NOT NULL,
    expenses NUMERIC(14,2) NOT NULL,
    debts NUMERIC(14,2) NOT NULL,
    closing_stock NUMERIC(14,2) NOT NULL,
    cash_received NUMERIC(14,2) NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    submitted_by_id INTEGER NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sensa_dailyentry_shop
        FOREIGN KEY (shop_id)
        REFERENCES sensa_shop (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sensa_dailyentry_submitted_by
        FOREIGN KEY (submitted_by_id)
        REFERENCES auth_user (id)
        ON DELETE SET NULL,
    CONSTRAINT unique_shop_entry_date
        UNIQUE (shop_id, entry_date),
    CONSTRAINT chk_opening_stock_non_negative CHECK (opening_stock >= 0),
    CONSTRAINT chk_stock_added_non_negative CHECK (stock_added >= 0),
    CONSTRAINT chk_expenses_non_negative CHECK (expenses >= 0),
    CONSTRAINT chk_debts_non_negative CHECK (debts >= 0),
    CONSTRAINT chk_closing_stock_non_negative CHECK (closing_stock >= 0),
    CONSTRAINT chk_cash_received_non_negative CHECK (cash_received >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sensa_dailyentry_entry_date
    ON sensa_dailyentry (entry_date);

CREATE INDEX IF NOT EXISTS idx_sensa_dailyentry_shop_id
    ON sensa_dailyentry (shop_id);

CREATE INDEX IF NOT EXISTS idx_sensa_dailyentry_submitted_by_id
    ON sensa_dailyentry (submitted_by_id);

-- ================================
-- Table: sensa_bankbalancesnapshot
-- ================================
CREATE TABLE IF NOT EXISTS sensa_bankbalancesnapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    provider VARCHAR(50) NOT NULL DEFAULT 'Jenga',
    account_reference VARCHAR(100) NOT NULL DEFAULT '',
    balance NUMERIC(14,2) NOT NULL,
    raw_response TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_sensa_bankbalancesnapshot_fetched_at
    ON sensa_bankbalancesnapshot (fetched_at DESC);

COMMIT;
