# Generated by Django 5.2.12 on 2026-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
