# Generated by Django 5.2.12 on 2026-03-11 14:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensa", "0003_dailyentry_sales_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyentry",
            name="sales_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total value sold for the day.",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
