# Generated by Django 5.2.12 on 2026-03-12 12:28

import sensa.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensa", "0004_alter_dailyentry_sales_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="JengaApiSettings",
            fields=[
                (
                    "id",
                    sensa.db_fields.SerensaAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(default="Jenga", max_length=50)),
                ("account_reference", models.CharField(max_length=100, unique=True)),
                ("auth_endpoint", models.URLField(blank=True)),
                ("balance_endpoint", models.URLField()),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_token", models.CharField(blank=True, max_length=255)),
                (
                    "grant_type",
                    models.CharField(default="client_credentials", max_length=50),
                ),
                ("scope", models.CharField(blank=True, max_length=255)),
                (
                    "balance_http_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "balance_field_path",
                    models.CharField(default="balance", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
