# Generated by Django 5.2.12 on 2026-03-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensa", "0005_jengaapisettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="api_token",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="auth_endpoint",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="balance_endpoint",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="balance_http_method",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="client_secret",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="grant_type",
        ),
        migrations.RemoveField(
            model_name="jengaapisettings",
            name="scope",
        ),
    ]
