# Generated by Django 5.2.12 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensa", "0006_remove_jengaapisettings_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_type",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("retail", "Retail"),
                    ("bar", "Bar"),
                    ("other", "Other"),
                ],
                default="retail",
                max_length=20,
            ),
        ),
    ]
