# Generated by Django 5.2.12 on 2026-03-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sensa", "0007_shop_shop_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name="shop",
            name="parent_shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subshops",
                to="sensa.shop",
            ),
        ),
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.UniqueConstraint(
                condition=models.Q(parent_shop__isnull=True),
                fields=("name",),
                name="unique_parent_shop_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.UniqueConstraint(
                condition=models.Q(parent_shop__isnull=False),
                fields=("parent_shop", "name"),
                name="unique_subshop_name_per_parent",
            ),
        ),
    ]
