# Generated by Django 5.2.12 on 2026-03-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sensa", "0008_shop_parent_hierarchy"),
    ]

    operations = [
        # Fix the UserProfile.user foreign key to point to sensa.User instead of auth.User
        # This handles cases where migrations ran with incorrect AUTH_USER_MODEL setting
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to='sensa.user'
            ),
        ),
    ]
